name: iOS Build

on: workflow_dispatch

jobs:
  build:
    name: iOS Build
    permissions: write-all
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.2
          
      - name: Install Libraries
        run: |
         haxelib install hmm --quiet
         haxelib run hmm setup --quiet
         haxelib run hmm install --quiet
         haxelib remove lime
         haxelib git lime https://github.com/FunkinCrew/lime mobile/main --quiet
         haxelib run lime rebuild hxcpp
      - name: Compile
        run: haxelib run lime build ios -nosign

      - name: Making ipa file
        run: |
          brew install ldid
          cd export/release/ios/build/Release-iphoneos/PsychMobile0.7.3.app
          ldid -S../../../PsychMobile0.7.3/PsychMobile0.7.3.entitlements PsychMobile0.7.3
          cd ..
          mkdir Payload
          mv PsychMobile0.7.3.app Payload
          zip -r PsychMobile0.7.3.ipa Payload
      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: Psych Engine iOS
          path: export/release/ios/build/Release-iphoneos/*.ipa
          if-no-files-found: error